<a href="https://colab.research.google.com/github/TaimoorAbdullah/Naive-Clasifier/blob/main/naiv_bayes_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes  import GaussianNB

In [ ]:
%cd /content/drive/MyDrive/Course Material/Supervised Machine Learning/Bayes Theorem and Naive Bayes Classifier

/content/drive/MyDrive/Course Material/Supervised Machine Learning/Bayes Theorem and Naive Bayes Classifier

In [ ]:
data  =  pd.read_csv('titanic_train.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
data.drop(['PassengerId','Name','Cabin','Ticket'] ,  inplace =  True , axis =  1)
data

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [ ]:
data.isnull().any()

Survived    False
Pclass      False
Sex         False
Age          True
SibSp       False
Parch       False
Fare        False
Embarked     True
dtype: bool

In [ ]:
data.fillna(value  = { "Age": data['Age'].mean()},inplace  =  True)

In [ ]:
data.isnull().any()

Survived    False
Pclass      False
Sex         False
Age          True
SibSp       False
Parch       False
Fare        False
Embarked     True
dtype: bool

In [ ]:
data.dropna(inplace =  True)
data.isnull().any()

Survived    False
Pclass      False
Sex         False
Age         False
SibSp       False
Parch       False
Fare        False
Embarked    False
dtype: bool

In [ ]:
data

     Survived  Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[889 rows x 8 columns]

In [ ]:
dummy = pd.get_dummies(data['Sex'])
dummy_1  = pd.get_dummies(data['Embarked'])

In [ ]:
new_data  = pd.concat([data,dummy,dummy_1],axis = 1)
new_data

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,female,male,C,Q,S
0,0,3,male,22.000000,1,0,7.2500,S,False,True,False,False,True
1,1,1,female,38.000000,1,0,71.2833,C,True,False,True,False,False
2,1,3,female,26.000000,0,0,7.9250,S,True,False,False,False,True
3,1,1,female,35.000000,1,0,53.1000,S,True,False,False,False,True
4,0,3,male,35.000000,0,0,8.0500,S,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,False,True,False,False,True
887,1,1,female,19.000000,0,0,30.0000,S,True,False,False,False,True
888,0,3,female,29.699118,1,2,23.4500,S,True,False,False,False,True
889,1,1,male,26.000000,0,0,30.0000,C,False,True,True,False,False
890,0,3,male,32.000000,0,0,7.7500,Q,False,True,False,True,False

In [ ]:
new_data = new_data.drop(['Sex','Embarked','female'],axis = 1 )
new_data

,Survived,Pclass,Age,SibSp,Parch,Fare,male,C,Q,S
0,0,3,22.000000,1,0,7.2500,True,False,False,True
1,1,1,38.000000,1,0,71.2833,False,True,False,False
2,1,3,26.000000,0,0,7.9250,False,False,False,True
3,1,1,35.000000,1,0,53.1000,False,False,False,True
4,0,3,35.000000,0,0,8.0500,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,True,False,False,True
887,1,1,19.000000,0,0,30.0000,False,False,False,True
888,0,3,29.699118,1,2,23.4500,False,False,False,True
889,1,1,26.000000,0,0,30.0000,True,True,False,False
890,0,3,32.000000,0,0,7.7500,True,False,True,False

In [ ]:
x =  new_data.drop('Survived',axis = 1).values
y = new_data['Survived'].values

In [ ]:

from sklearn.preprocessing import StandardScaler
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size = 0.2,random_state  = 42)
sc  =  StandardScaler()
sc.fit_transform(x_train)
sc.transform(x_test)

naiv = GaussianNB()
naiv.fit(x_train,y_train)

GaussianNB()